Add function to filter keys by prefix
deso-protocol/state-consumer pull request #6
Opened 2024-02-15 23:28 UTC by lazynina

2024-02-15 23:28 UTC, lazynina commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/deso-protocol/state-consumer/6?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

Current dependencies on/for this PR:
* `main`
  * **PR #4** <a href="https://app.graphite.dev/github/pr/deso-protocol/state-consumer/4?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #6** <a href="https://app.graphite.dev/github/pr/deso-protocol/state-consumer/6?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/deso-protocol/state-consumer/6?utm_source=stack-comment).

2024-02-16 14:56 UTC, superzordon requested changes
Small refactor, otherwise looks good!

2024-02-16 14:56 UTC, superzordon commented on consumer/batching.go
> +func FilterKeysByPrefix(keys [][]byte, prefix []byte) [][]byte {
Function looks great - though it doesn't really have a lot to do with the batching process - can we move this to the helpers file?

2024-02-16 21:00 UTC, superzordon approved these changes

2024-02-16 21:01 UTC, merged